kubernetes:
  namespaces: default
  threshold:
    ram: 50
  exeptions:
    deployments: [dolphin-backend, jaguar-backend , panda-backend]
slack:
  notify: false
  webhookurl: ""
  channel: "topwatcher"
  username: "topwatcher"
