kubernetes:
  kubeconfig: /home/hamid/.kube/config
  namespaces: default
  podrestart: false
  threshold:
    ram: 5
  exceptions:
    deployments:
      - web3
      - web
      - web1
      - web2
      - web3
      - web4
slack:
  notify: false
  webhookurl: ""
  channel: "topwatcher"
  username: "topwatcher"

logging:
  debug: true