kubernetes:
  inside-cluster: true
  namespaces: default
  threshold:
    ram: 5
  exeptoions:
    deployments:
      - dolphin-backend
      - jaguar-backend
      - panda-backend
slack:
  notify: false
  webhookurl: ""
  channel: "topwatcher"
  username: "topwatcher"
