kubernetes:
  namespaces: default
  threshold:
    ram: 5
  exceptions:
    deployments:
      - web3
slack:
  notify: false
  webhookurl: ""
  channel: "topwatcher"
  username: "topwatcher"

logging:
  debug: false