apiVersion: v1
data:
  config.yaml: |-
    kubernetes:
      kubeconfig: /path/to/kube/config
      namespaces: default
      podrestart: false
      threshold:
        ram: 5
      exceptions:
        deployments:
          - deployment1
          - deployment2
    slack:
      notify: false
      webhookurl: ""
      channel: ""
      username: "topwatcher"
    
    logging:
      debug: false
kind: ConfigMap
metadata:
  labels:
    group: backend
  name: topwatcher-configmap
  namespace: default
