apiVersion: batch/v1
kind: CronJob
metadata:
  name: topwatcher
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /usr/local/bin/topwatcher
            - /app/config.yaml
            image: topwatcher:latest
            imagePullPolicy: IfNotPresent
            name: topwatcher
            volumeMounts:
            - mountPath: /app/config.yaml
              name: topwatcher-configmap
              subPath: config.yaml
            - mountPath: /app/kubeconfig
              name: cluster-config
              subPath: config
          restartPolicy: OnFailure
          volumes:
          - configMap:
              defaultMode: 420
              items:
              - key: config.yaml
                path: config.yaml
              name: topwatcher-configmap
            name: topwatcher-configmap
          - name: cluster-config
            secret:
              defaultMode: 420
              secretName: cluster-config
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 1
  suspend: false
