apiVersion: batch/v1
kind: CronJob
metadata:
  name: topwatcher
  namespace: default
spec:
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 60
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /usr/local/bin/topwatcher
            - start
            - -c
            - /app_topwatcher/config.yaml
            image: ghcr.io/hamidaria70/topwatcher:v0.2.0
            imagePullPolicy: Always
            name: topwatcher
            volumeMounts:
            - mountPath: /app_topwatcher/config.yaml
              name: topwatcher-configmap
              subPath: config.yaml
            - mountPath: /app_topwatcher/kubeconfig
              name: cluster-config
              subPath: config
          restartPolicy: OnFailure
          volumes:
          - configMap:
              defaultMode: 420
              items:
              - key: config.yaml
                path: config.yaml
              name: topwatcher-configmap
            name: topwatcher-configmap
          - name: cluster-config
            secret:
              defaultMode: 420
              secretName: cluster-config
  schedule: '*/15 * * * *'
  successfulJobsHistoryLimit: 1
  suspend: false
