name: Docker CI

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  REGISTRY: ghcr.io

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Go

      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Test
      run: |
        echo "Under Construction..."
    
    - name: Docker Login
      run: |
        echo ${{ vars.PACKAGES_TOKEN }} | docker login $REGISTRY -u ${{ vars.PACKAGES_USER }} --password-stdin

    - name: Build the Docker image
      env:
        IMAGE_NAME: ${{ github.repository }}
      run: |
        IMAGE_TAG=$(echo $GITHUB_REF_NAME | sed 's+/+-+g')
        docker build . -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
